from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from uuid import UUID, uuid4
from datetime import datetime, date
from enum import Enum

class JobStatus(str, Enum):
    """
    Enum for the status of an analysis job.
    """
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class AnalysisJob(BaseModel):
    """
    Represents an analysis job, tracking its status and metadata.
    """
    job_id: UUID = Field(default_factory=uuid4, description="Unique identifier for the analysis task.")
    status: JobStatus = Field(default=JobStatus.PENDING, description="The current status of the job.")
    error_message: Optional[str] = Field(default=None, description="A descriptive message if the job failed.")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="The timestamp when the job was created.")

class Transaction(BaseModel):
    """
    Represents a single financial transaction extracted from the user's file.
    """
    id: UUID = Field(default_factory=uuid4, description="A unique identifier for the transaction within our system.")
    date: date = Field(description="The date the transaction occurred.")
    description: str = Field(description="The original transaction description/memo.")
    amount: float = Field(description="The monetary value of the transaction. Can be positive or negative.")
    currency: str = Field(default="USD", description="The currency code (e.g., 'USD').")
    category: str = Field(default="Uncategorized", description="The expense category assigned by the AI model.")

class InsightType(str, Enum):
    """
    Enum for the type of financial insight.
    """
    SPENDING_PATTERN = "SPENDING_PATTERN"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"

class Insight(BaseModel):
    """
    Represents a structured piece of financial information generated by the system.
    """
    type: InsightType = Field(description="The type of insight (e.g., spending pattern, anomaly).")
    title: str = Field(description="A short, human-readable title for the insight.")
    description: str = Field(description="A detailed explanation of the insight.")
    data: Dict[str, Any] = Field(description="A flexible dictionary containing supporting data for the insight.")

class Prediction(BaseModel):
    """
    Represents a forecast of future spending.
    """
    period: str = Field(description="The time period for the prediction (e.g., '2025-12').")
    predicted_amount: float = Field(description="The total predicted spending for the period.")
    confidence_score: float = Field(description="A score between 0 and 1 indicating the model's confidence in the prediction.")
